list1=['mot','hai','ba','bon']
list1.append('nam')
print(list1)
list1.insert(4,'sau')
print(list1)
list1.extend(['bay','tam'])
print(list1)
print("chi muc cua 'mot' la ",list1.index('mot'))
list1.remove('hai')
print(list1)
list1.sort()
print(list1)
list1.reverse()
print(list1)
list1.pop()
print(list1)